version: '3.8'

services:
  payment_system_db:
    container_name: payment_system_db
    image: postgres
    environment:
      POSTGRES_DB: payment_system_db
      POSTGRES_USER: payment_system
      POSTGRES_PASSWORD: payment_system
      PGDATA: /data/payment_system
    volumes:
      - payment_system_data:/data/payment_system
    ports:
      - "5432:5432"
    networks:
      - payment_system_network

  payment_system_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - payment_system_db
    networks:
      - payment_system_network

volumes:
  payment_system_data:

networks:
  payment_system_network:
    driver: bridge