spring:
  application:
    name: Payment System
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/payment_system_db
    username: payment_system
    password: payment_system
